apiVersion: apps/v1
kind: Deployment
metadata:
  name: box
  labels:
    app: box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: box
  template:
    metadata:
      labels:
        app: box
    spec:
      containers:
      - name: box
        image: juixtu/box:v1
        ports:
        - name: box
          containerPort: 8080
